apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitraf

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  # Uncomment to enable ingress
  # - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: gitraf
    includeSelectors: true

images:
  - name: gitraf-server
    newName: gitraf-server
    newTag: latest
