apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy all gitraf components
# Usage: kubectl apply -k kubernetes/base/

resources:
  - namespace.yaml
  - ../gitraf-server
  - ../gitraf-core
  - ../nginx

commonLabels:
  app.kubernetes.io/part-of: gitraf
  app.kubernetes.io/managed-by: kustomize
