apiVersion: v1
kind: ConfigMap
metadata:
  name: ogit-config
  namespace: gitraf
  labels:
    app.kubernetes.io/name: ogit
    app.kubernetes.io/component: git-backend
data:
  config.yaml: |
    http:
      port: 8080
      logs: true
    ssh:
      enabled: false
    logger:
      level: info
      pretty: false
    storage:
      type: local
      local:
        path: /data/repos
