apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitraf

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: gitraf
